# https://aka.ms/yaml

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - Settings/*
    exclude:
    - products/**
    - pipelines/**

pr: 
  autoCancel: false
  branches:
    include:
    - main
    - alfred*
  paths:
    include:
    - Settings/*
    exclude:
    - products/**

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Synapse workspace deployment@2
  inputs:
    operation: 'deploy'
    azureSubscription: 'WIFC'
    TargetWorkspaceName: 
    DeleteArtifactsNotInTemplate: false
    DeployManagedPrivateEndpoints: false
    FailOnMissingOverrides: false
    Environment: 'prod'
    npmpackage: 'prod'